name: ednn_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - xarray
  - cartopy
  - scipy
  - tensorflow
  - pip
  - pip:
      - git+https://github.com/kachingasilwimba/miles-guess.git
      - SALib
      - keras
